$(document).ready(function(){
    $('input').ready(function(){
        $('#departing').datepicker();
        $('#returning').datepicker();
    });
    $('#submit').mouseenter(function(){
        $(this).fadeTo('fast',0.5);
    })
    $('#submit').mouseleave(function(){
        $(this).fadeTo('fast',1.0);
    })
})